import React, { createContext, useContext } from 'react';

interface Translations {
  [key: string]: string;
}

const translations: Translations = {
  "apply_download": "申请下载",
  "appointment_cooperation": "预约合作",
  "back_home": "返回首页",
  "breadcrumb_content": "新闻",
  "breadcrumb_home": "首页",
  "business_environment_index_report": "业务环境指数报告",
  "business_environment_service": "数字营商",
  "business_environment_service_desc": "为企业提供一流的数字营商环境",
  "changxing_city": "长兴县",
  "changxing_desc": "长兴是我们的一个重要合作城市",
  "changzhou_city": "常州市",
  "changzhou_city_short": "常州",
  "changzhou_desc": "常州是我们的一个重要合作城市",
  "changxing_city_short": "长兴",
  "city_baoji": "宝鸡",
  "city_baotou": "包头",
  "city_beihai": "北海",
  "city_chamdo": "昭业",
  "city_changchun": "长春",
  "city_changsha": "长沙",
  "city_changxing": "长兴",
  "city_changzhou": "常州",
  "city_chengdu": "成都",
  "city_chongqing": "重庆",
  "city_dali": "大理",
  "city_dalian": "大连",
  "city_datong": "大同",
  "city_dujiangyan": "都江堰",
  "city_fuzhou": "福州",
  "city_ganzhou": "赣州",
  "city_guilin": "桂林",
  "city_guiyang": "贵阳",
  "city_haikou": "海口",
  "city_hanzhong": "汉中",
  "city_harbin": "哈尔滨",
  "city_hefei": "合肥",
  "city_hengyang": "衡阳",
  "city_hohhot": "呼和浩特",
  "city_jinan": "济南",
  "city_jiuquan": "酒泉",
  "city_kashgar": "喀什",
  "city_kunming": "昆明",
  "city_lanzhou": "兰州",
  "city_lhasa": "拉萨",
  "city_liuzhou": "柳州",
  "city_luoyang": "洛阳",
  "city_mianyang": "绵阳",
  "city_nanchang": "南昌",
  "city_nanning": "南宁",
  "city_nantong": "南通",
  "city_nyingchi": "林芝",
  "city_qingdao": "青岛",
  "city_quanzhou": "泉州",
  "city_shaoxing": "绍兴",
  "city_shenyang": "沈阳",
  "city_shigatse": "日喀则",
  "city_shijiazhuang": "石家庄",
  "city_taiyuan": "太原",
  "city_tangshan": "唐山",
  "city_tianshui": "天水",
  "city_urumqi": "乌鲁木齐",
  "city_weifang": "潍坊",
  "city_wenzhou": "温州",
  "city_wuhan": "武汉",
  "city_wuhu": "芜湖",
  "city_xiamen": "厦门",
  "city_xian": "西安",
  "city_xianyang": "咸阳",
  "city_xining": "西宁",
  "city_xuzhou": "徐州",
  "city_yanan": "延安",
  "city_yangzhou": "扬州",
  "city_yantai": "烟台",
  "city_yichang": "宜昌",
  "city_yili": "伊犁",
  "city_yinchuan": "银川",
  "city_yueyang": "岳阳",
  "city_yulin": "榆林",
  "city_zhengzhou": "郑州",
  "city_zhuhai": "珠海",
  "city_zunyi": "遵义",
  "column_navigation": "栏目导航",
  "column_navigation_title": "栏目导航",
  "company_name": "企来集团",
  "company_name_with_logo": "企来集团",
  "company_subtitle": "新闻中心",
  "cooperation_overview": "合作概况",
  "copyright": "版权信息",
  "copyright_unit": "版权方",
  "core_business": "8大核心业务",
  "data_asset_registration": "数据资产登记",
  "data_asset_registration_desc": "为企业和政府部门提供数据资产登记和管理服务",
  "public_data_authorization": "公共数据授权",
  "public_data_authorization_desc": "推动公共数据的安全授权和流通使用",
  "industry_brain_construction": "产业大脑建设",
  "industry_brain_construction_desc": "为产业园区和企业建设数据驱动的产业大脑",
  "cross_border_data_flow_service": "跨境数据流动服务",
  "cross_border_data_flow_desc": "支持国际数据流动和跨境数据合作",
  "data_trading_matching": "数据交易撮合",
  "data_trading_matching_desc": "提供数据交易平台和撮合服务",
  "digital_government_consulting": "数字政府咨询",
  "digital_government_consulting_desc": "为政府部门提供数字化转型咨询服务",
  "data_security_assessment": "数据安全评估",
  "data_security_assessment_desc": "提供数据安全评估和风险防控服务",
  "digital_talent_training": "数字人才培训",
  "digital_talent_training_desc": "培养数字经济领域的专业人才",
  "comprehensive_support": "为政府、企业和社会提供全方位的数字化赋能",
  "core_business_segments": "一级业务段",
  "core_strategic_node": "核心战略节点",
  "core_strategic_partner_desc": "核心战略合作城市",
  "covered_cities_count": "合作城市数",
  "cross_border_data_circulation": "跨境数据流动",
  "data_element_assetization": "数据要素资产化",
  "data_element_empowerment": "数据要素赋能服务",
  "data_element_reform_cases": "数据要素改革案例",
  "data_name": "数据名称",
  "data_openness": "数据开放",
  "data_trading": "数据交易",
  "digital_economy_white_paper": "数字经济白皮书",
  "digital_governance": "数字监管",
  "digital_government_construction": "数字政府建设",
  "digital_investment": "数字招商",
  "digital_investment_promotion": "数字招商",
  "digital_investment_promotion_desc": "为整个社会经济提供数字招商服务",
  "digital_services": "数字服务",
  "digital_services_intro": "企来集团为政府、企业、整个社会提供全方位的数字化转型服务",
  "digital_services_link": "数字服务",
  "digital_services_title": "数字服务",
  "digital_supervision_service": "数字监管",
  "digital_supervision_service_desc": "为政府部门提供数字监管服务",
  "driven_investment_count": "带动投资额",
  "editor_info": "编辑信息",
  "expansion_cooperation_node": "拓展合作节点",
  "footer_about": "关于我们",
  "footer_contact": "联系我们",
  "footer_copyright_full": "版权所有 2024 企来集团 保留所有权利",
  "footer_privacy": "隐私政策",
  "footer_terms": "服务条款",
  "format": "格式",
  "group_overview": "集团概况",
  "group_overview_nav": "集团概况",
  "group_overview_p1": "企来集团是一家专注于数字经济领域的战略性集团",
  "group_overview_p2": "企来集团为整个社会经济打造数字经济新体系",
  "group_overview_title": "集团概况",
  "industrial_park_digital_investment": "产业园区数字招商",
  "interaction_intro": "欢迎您的建议和反馈",
  "interaction_title": "互动交流",
  "interactive_exchange": "互动交流",
  "key_expansion_area_desc": "重点拓展区域",
  "landed_projects_count": "落地项目数",
  "lanzhou_city": "兰州市",
  "lanzhou_city_short": "兰州",
  "lanzhou_desc": "兰州是我们的一个重要合作城市",
  "local_cooperation": "地方合作",
  "local_cooperation_intro": "了解我们的地方合作情况",
  "local_cooperation_nav": "地方合作",
  "local_cooperation_title": "地方合作",
  "national_emblem_alt": "国徽",
  "national_network": "全国网络格局",
  "national_network_layout": "全国网络格局",
  "nav_about": "集团概况",
  "nav_cooperation": "地方合作",
  "nav_data": "数据开放",
  "nav_home": "首页",
  "nav_interaction": "互动交流",
  "nav_network": "全国网络格局",
  "nav_news": "新闻中心",
  "nav_services": "数字服务",
  "news_category": "新闻分类",
  "news_date": "发布日期",
  "news_focus": "新闻聚焦",
  "news_not_found": "新闻未找到",
  "news_source": "信息来源",
  "open_data_intro": "了解我们的数据开放情况",
  "open_data_link": "数据开放",
  "open_data_title": "数据开放",
  "operation": "操作",
  "policy_documents": "政策文件",
  "policy_news": "政策要闻",
  "policy_news_intro": "了解最新的政策资讯和行业动态",
  "policy_news_title": "政策要闻",
  "print_btn": "打印",
  "publish_time": "发布时间",
  "qilai_group_source": "企来集团",
  "read_more": "查看详情",
  "release_date": "发布日期",
  "return_to_home": "返回首页",
  "return_to_home_btn": "返回首页",
  "search_button": "搜索",
  "search_placeholder": "请输入关键字查询",
  "share_btn": "分享",
  "smart_city": "智慧城市",
  "source": "来源",
  "sponsor": "主办方",
  "sponsor_unit": "主办方",
  "submit_button": "提交",
  "submit_intent": "提交意向",
  "system_maintenance": "系统维护中",
  "view_national_network": "查看全国合作网络格局",
  "xiamen_city": "厦门市",
  "xiamen_city_short": "厦门",
  "xiamen_desc": "厦门是我们的一个重要合作城市",
  "yueyang_city": "岳阳市",
  "yueyang_city_short": "岳阳",
  "yueyang_desc": "岳阳是我们的一个重要合作城市",
  "zhuhai_city": "珠海市",
  "zhuhai_city_short": "珠海",
  "zhuhai_desc": "珠海是我们的一个重要合作城市",
}

interface LanguageContextType {
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const t = (key: string) => translations[key] || key;

  return (
    <LanguageContext.Provider value={{ t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
